## Usa l'immagine di base di OpenJDK per Java 17
#FROM openjdk:17
#EXPOSE 8080
#
## Copia il file JAR del tuo progetto nella directory /app all'interno del container
#COPY target/HomeChef-0.0.1-SNAPSHOT.jar /app/app.jar
#
## Imposta la directory di lavoro all'interno del container
#WORKDIR /app
#
## Esponi la porta sulla quale il tuo servizio Spring Boot è in ascolto (aggiorna con la porta corretta)
#EXPOSE 8080
#
## Comando per avviare l'applicazione Spring Boot quando il container viene eseguito
#CMD ["java", "-jar", "app.jar"]